[general]
static=yes
writeprotect=no

; pjsip.conf の context=internal と一致させること
[internal]
; 内線 1001 への発信
exten => 1001,1,Dial(PJSIP/1001,30)
exten => 1001,n,Hangup()

; 内線 1002 への発信
exten => 1002,1,Dial(PJSIP/1002,30)
exten => 1002,n,Hangup()
